services:
  - type: web
    name: kanban-backend
    env: docker
    plan: free
    root: backend
    dockerfilePath: backend/Dockerfile
    buildCommand: docker build -t kanban-backend .
    startCommand: docker run -p 8000:8000 kanban-backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
